application: apt-project
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/fonts
  static_dir: assets/fonts

# process handlers

- url: /view_picture/([^/]+)?
  script: handlers.ViewPictureHandler.app
#  script: RestaurantRegisterHandler.app

# page handler

- url: /restaurantregister
  script: RestaurantRegisterHandler.app

- url: /register
  script: RestaurantRegisterHandler.app

- url: /viewnearby
  script: ViewNearbyHandler.app

- url: /location
  script: LocationHandler.app

- url: /option
  script: OptionHandler.app

- url: /main_restaurant
  script: Main_Restaurant.app

- url: /main
  script: MainHandler.app
  login: required

- url: /option_get
  script: OptionHandler.app

- url: /option
  script: OptionHandler.app

- url: /.*
  script: LoginHandler.app
  #slogin: required

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: latest

- name: jinja2
  version: latest