application: sacred-highway-108321
#application: ross-1084
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: latest

- name: jinja2
  version: latest