application: apt-project-1152
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/fonts
  static_dir: assets/fonts

- url: /assets/images
  static_dir: assets/images

# process handlers
- url: /evaluate
  script: RestaurantHandler.app

- url: /getuserinfo.*
  script: RestaurantHandler.app

- url: /restaurantregister
  script: RestaurantRegisterHandler.app
  login: required

- url: /view_picture/([^/]+)?
  script: handlers.ViewPictureHandler.app
  login: required
#  script: RestaurantRegisterHandler.app

- url: /dish_handler
  script: AddDishHandler.app
  login: required

# page handler
- url: /viewcart
  script: CartHandler.app
  login: required

- url: /cart
  script: CartHandler.app
  login: required

- url: /viewdishes.*
  script: ViewDishesHandler.app
  login: required

- url: /add_dish.*
  script: AddDishHandler.app
  login: required

- url: /restaurantregister
  script: RestaurantRegisterHandler.app
  login: required

- url: /register
  script: RestaurantRegisterHandler.app
  login: required

- url: /viewnearby
  script: ViewNearbyHandler.app
  login: required

- url: /location
  script: LocationHandler.app
  login: required

- url: /order.*
  script: OrderHandler.app
  login: required


- url: /main_restaurant
  script: Main_Restaurant.app
  login: required

- url: /main
  script: MainHandler.app
  login: required

- url: /option_get
  script: OptionHandler.app

- url: /option
  script: OptionHandler.app

- url: /error
  script: ErrorHandler.app

- url: /.*
  script: LoginHandler.app
  #login: required

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: latest

- name: jinja2
  version: latest