application: apt-project
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/css
  static_dir: assets/css

- url: /assets/js
  static_dir: assets/js

- url: /assets/fonts
  static_dir: assets/fonts

- url: /main
  script: MainHandler.app
  login: required

- url: /.*
  script: LoginHandler.app
  #slogin: required

libraries:
- name: webapp2
  version: latest

- name: PIL
  version: latest

- name: jinja2
  version: latest